name: campus_lost_found
description: "Campus Lost and Found application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  uuid: ^4.3.3
  intl: ^0.19.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/uogcampusimage.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
